@startuml
skinparam classAttributeIconSize 0

' ===== Interface =====
interface "Comparable<Werkstoffprobe>" as ComparableM

abstract class Werkstoffprobe {
  - id : String
  - bezeichnung : String
  - dichte : double
  - masse : double

  + Werkstoffprobe(id:String, bezeichnung:String, dichte:double, masse:double)

  + getId() : String
  + setId(id:String) : void
  + getBezeichnung() : String
  + setBezeichnung(b:String) : void
  + getDichte() : double
  + setDichte(d:double) : void
  + getMasse() : double
  + setMasse(m:double) : void

  + berechneVolumen() : double
  + berechneMaterialwert() : double
  {abstract} + berechneQualitaetsIndex() : double

  + compareTo(other:Werkstoffprobe) : int
  + equals(o:Object) : boolean
  + hashCode() : int
  + toString() : String
}

class MetallProbe {
  - zugfestigkeit : double
  - korrosionsWert : double

  + MetallProbe(...)

  + getZugfestigkeit() : double
  + setZugfestigkeit(z:double) : void
  + getKorrosionsWert() : double
  + setKorrosionsWert(k:double) : void

  + berechneQualitaetsIndex() : double
  + toString() : String
}

Werkstoffprobe ..|> ComparableM

class PolymerProbe {
  - glasuebergangsTemp : double

  + PolymerProbe(...)

  + getGlasuebergangsTemp() : double
  + setGlasuebergangsTemp(t:double) : void

  + berechneQualitaetsIndex() : double
  + toString() : String
}

class KeramikProbe {

  + KeramikProbe(...)

  + berechneQualitaetsIndex() : double
  + toString() : String
}

class WerkstoffQualitaetsIndexComparator {
  + compare(o1:Werkstoffprobe, o2:Werkstoffprobe) : int
}

class WerkstoffzentrumVerwaltung {
  - proben : LinkedList<Werkstoffprobe>

  + WerkstoffzentrumVerwaltung()

  + addProbe(probe:Werkstoffprobe) : boolean
  + removeProbeById(id:String) : boolean
  + removeAllByTyp(typName:String) : int
  + removeAllMitIndexUnter(grenzwert:double) : int

  + findById(id:String) : Werkstoffprobe
  + druckeStatistik() : void

  + sortiereStandard() : void
  + sortiereNachQualitaetsIndex() : void
}

Werkstoffprobe <|-- MetallProbe
Werkstoffprobe <|-- PolymerProbe
Werkstoffprobe <|-- KeramikProbe

WerkstoffzentrumVerwaltung o-- "0..*" Werkstoffprobe

WerkstoffQualitaetsIndexComparator ..> Werkstoffprobe

@enduml